<?php

/**
 * Created by PhpStorm.
 * User: LC
 * Date: 15/01/2016
 * Time: 15:37
 */
require_once standart_system_pfad.'server_skript/base/Bergmann.php';
class wahle_eine_benutzer_von_email extends Bergmann
{
    private $email;
    public function erhalten_daten()
    {
        // TODO: Implement erhalten_daten() method.
        return $this->ergebnis;
    }

    protected function daten_leere()
    {
        // TODO: Implement daten_leere() method.
    }

    protected function daten_uberprufen()
    {
        // TODO: Implement daten_uberprufen() method.
        return true;
    }
    public function satz_email($email)
    {
        $this->email = $email;
    }

    protected function vorbereiten_abfrage_und_parameter()
    {
        // TODO: Implement vorbereiten_abfrage_und_parameter() method.
        $this->abfrage = 'SELECT sg_user.id, sg_user.username FROM sg_user JOIN detail_sg_user ON sg_user.id = detail_sg_user.id WHERE detail_sg_user.email = ?';
        $this->parameter = array($this->email);
    }
    protected function ist_token_korrigieren()
    {
        return true;
        //return parent::ist_token_korrigieren(); // TODO: Change the autogenerated stub
    }
}