<?php

/**
 * Created by PhpStorm.
 * User: LC
 * Date: 13/12/2015
 * Time: 12:01
 */
require_once standart_system_pfad.'server_skript/base/Bergmann.php';
class wahle_allen_benutzer extends Bergmann
{
    protected $seite;
    public function erhalten_daten()
    {
        // TODO: Implement erhalten_daten() method.
        return $this->ergebnis;
    }

    protected function daten_leere()
    {
        // TODO: Implement daten_leere() method.
    }

    protected function daten_uberprufen()
    {
        // TODO: Implement daten_uberprufen() method.
        $this->seite = filter_input(INPUT_GET, parameter_anzaigen_einstellung_benutzer_numerische_seite, FILTER_VALIDATE_INT);
        if($this->seite === false || $this->seite === null) $this->seite = 0; else $this->seite = --$this->seite*anzaigen_enstellung_benutzer_seite_max_zeile;
        return true;
    }

    protected function vorbereiten_abfrage_und_parameter()
    {
        // TODO: Implement vorbereiten_abfrage_und_parameter() method.
        $this->abfrage =  'SELECT
sg_user.id,
sg_user.username,
detail_sg_user.email,
jenis_user.jenis,
jenis_user.id_jenis,
CASE WHEN jenis_user.id_jenis = 3 THEN
(SELECT '.kspo_daten_bank_name.'.tblpropinsi.Propinsi FROM '.daten_bank_name.'.user_tingkat_provinsi JOIN '.kspo_daten_bank_name.'.tblpropinsi
 ON '.kspo_daten_bank_name.'.tblpropinsi.IdPropinsi = '.daten_bank_name.'.user_tingkat_provinsi.id_provinsi WHERE '.daten_bank_name.'.user_tingkat_provinsi.id = sg_user.id)
 ELSE
 (SELECT
'.kspo_daten_bank_name.'.tblpropinsi.Propinsi
  FROM '.daten_bank_name.'.user_tingkat_kabupaten_kota
  LEFT JOIN '.kspo_daten_bank_name.'.tblkabupaten ON  '.kspo_daten_bank_name.'.tblkabupaten.IdKabupaten = '.daten_bank_name.'.user_tingkat_kabupaten_kota.id_kabupaten_kota
  LEFT JOIN '.kspo_daten_bank_name.'.tblpropinsi ON  '.kspo_daten_bank_name.'.tblpropinsi.IdPropinsi = '.kspo_daten_bank_name.'.tblkabupaten.IdPropinsi
  WHERE '.daten_bank_name.'.user_tingkat_kabupaten_kota.id = sg_user.id)
 END AS provinsi,


(SELECT '.kspo_daten_bank_name.'.tblkabupaten.Kabupaten FROM '.daten_bank_name.'.user_tingkat_kabupaten_kota JOIN '.kspo_daten_bank_name.'.tblkabupaten ON  '.kspo_daten_bank_name.'.tblkabupaten.IdKabupaten = '.daten_bank_name.'.user_tingkat_kabupaten_kota.id_kabupaten_kota WHERE '.daten_bank_name.'.user_tingkat_kabupaten_kota.id = sg_user.id) AS kabupaten,
detail_sg_user.alamat,
detail_sg_user.no_telp,
detail_sg_user.no_fax,
detail_sg_user.path_picture,
CASE WHEN jenis_user.id_jenis = 3 THEN
(SELECT '.kspo_daten_bank_name.'.tblpropinsi.IdPropinsi FROM '.daten_bank_name.'.user_tingkat_provinsi JOIN '.kspo_daten_bank_name.'.tblpropinsi
 ON '.kspo_daten_bank_name.'.tblpropinsi.IdPropinsi = '.daten_bank_name.'.user_tingkat_provinsi.id_provinsi WHERE '.daten_bank_name.'.user_tingkat_provinsi.id = sg_user.id)
 ELSE
 (SELECT
'.kspo_daten_bank_name.'.tblpropinsi.IdPropinsi
  FROM '.daten_bank_name.'.user_tingkat_kabupaten_kota
  LEFT JOIN '.kspo_daten_bank_name.'.tblkabupaten ON  '.kspo_daten_bank_name.'.tblkabupaten.IdKabupaten = '.daten_bank_name.'.user_tingkat_kabupaten_kota.id_kabupaten_kota
  LEFT JOIN '.kspo_daten_bank_name.'.tblpropinsi ON  '.kspo_daten_bank_name.'.tblpropinsi.IdPropinsi = '.kspo_daten_bank_name.'.tblkabupaten.IdPropinsi
  WHERE '.daten_bank_name.'.user_tingkat_kabupaten_kota.id = sg_user.id)
 END AS id_provinsi,
 (SELECT '.kspo_daten_bank_name.'.tblkabupaten.IdKabupaten FROM '.daten_bank_name.'.user_tingkat_kabupaten_kota JOIN '.kspo_daten_bank_name.'.tblkabupaten ON  '.kspo_daten_bank_name.'.tblkabupaten.IdKabupaten = '.daten_bank_name.'.user_tingkat_kabupaten_kota.id_kabupaten_kota WHERE '.daten_bank_name.'.user_tingkat_kabupaten_kota.id = sg_user.id) AS id_kabupaten
FROM sg_user
LEFT JOIN jenis_user ON sg_user.id_jenis = jenis_user.id_jenis
LEFT JOIN detail_sg_user ON sg_user.id = detail_sg_user.id
WHERE sg_user.active = 1
ORDER BY sg_user.id LIMIT '.$this->seite.', '.anzaigen_enstellung_benutzer_seite_max_zeile;
    }

    protected function ist_token_korrigieren()
    {
        return true;
        //return parent::ist_token_korrigieren(); // TODO: Change the autogenerated stub
    }
}