<?php

/**
 * Created by PhpStorm.
 * User: LC
 * Date: 09/01/2016
 * Time: 12:38
 */
require_once standart_system_pfad.'server_skript/base/Bergmann.php';
class wahle_benutzer_perfil extends Bergmann
{
    public function erhalten_daten()
    {
        // TODO: Implement erhalten_daten() method.
        return $this->ergebnis;
    }

    protected function daten_leere()
    {
        // TODO: Implement daten_leere() method.
    }

    protected function daten_uberprufen()
    {
        // TODO: Implement daten_uberprufen() method.
        return true;
    }

    protected function vorbereiten_abfrage_und_parameter()
    {
        // TODO: Implement vorbereiten_abfrage_und_parameter() method.
        $this->abfrage = 'SELECT email, alamat, no_telp, no_fax, path_picture FROM detail_sg_user WHERE id = ?;';
        $this->parameter = array($_SESSION[id_benutzername]);
    }
    protected function ist_token_korrigieren()
    {
        return true;
        //return parent::ist_token_korrigieren(); // TODO: Change the autogenerated stub
    }
}