<?php

/**
 * Created by PhpStorm.
 * User: LC
 * Date: 27/12/2015
 * Time: 19:00
 */
require_once standart_system_pfad.'server_skript/base/globale_variable.php';
require_once standart_system_pfad.'server_skript/daten_bank_json/Bergmann_json.php';
abstract class Base_vergleichen_einfugen extends Bergmann_json
{
    public function erhalten_daten()
    {
        // TODO: Implement erhalten_daten() method.
        $this->json->hinzufugen(json_einfugen_vergleichen, $this->ergebnis[0][0]);
    }
    protected function daten_leere()
    {
        // TODO: Implement daten_leere() method.
    }
    protected function daten_uberprufen()
    {
        // TODO: Implement daten_uberprufen() method.
        if(!$this->ist_null(filter_input(INPUT_GET, einfugen_jahr), filter_input(INPUT_GET, einfugen_monat),
            filter_input(INPUT_GET, einfugen_provinz), filter_input(INPUT_GET, einfugen_kabupaten),
            filter_input(INPUT_GET, einfugen_bentuk), filter_input(INPUT_GET, einfugen_model)))
        {
            return true;
        }
        return false;
    }
    protected function ist_token_korrigieren()
    {
        return true;
        //return parent::ist_token_korrigieren(); // TODO: Change the autogenerated stub
    }
}