<?php

/**
 * Created by PhpStorm.
 * User: LC
 * Date: 17/01/2016
 * Time: 19:41
 */
class uberprufen_einfugen_vonhanden extends Bergmann
{
    public function erhalten_daten()
    {
        // TODO: Implement erhalten_daten() method.
        if((int)$this->ergebnis[0][0] > 0)
            return true;
        else return false;
    }

    protected function daten_leere()
    {
        // TODO: Implement daten_leere() method.
    }

    protected function daten_uberprufen()
    {
        // TODO: Implement daten_uberprufen() method.
        return true;
    }

    protected function vorbereiten_abfrage_und_parameter()
    {
        // TODO: Implement vorbereiten_abfrage_und_parameter() method.
        $this->abfrage = 'SELECT COUNT(*)  FROM rekap WHERE tanggal = ? AND id_propinsi = ? AND id_kabupaten_kota = ? AND id_model = ? AND id_bentuk = ?';
    }
    public function satz_daten($daten)
    {
        $this->parameter = $daten;
    }
    protected function ist_token_korrigieren()
    {
        return true;
        //return parent::ist_token_korrigieren(); // TODO: Change the autogenerated stub
    }
}